import React, { useState } from 'react';
import './CookLogin.css'; 

const CookLogin = () => {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [restaurantName, setRestaurantName] = useState('');
  const [menuItems, setMenuItems] = useState([
    { id: 4321, name: '', price: '' }, // Initial item with autogenerated ID
  ]);

  const handleEmailChange = (e) => {
    setEmail(e.target.value);
  };

  const handlePasswordChange = (e) => {
    setPassword(e.target.value);
  };

  const handleLoginClick = () => {
    if (email && password) {
      setShowForm(true);
    } else {
      window.alert('Please enter both email and password.');
    }
  };

  const handleRestaurantNameChange = (e) => {
    setRestaurantName(e.target.value);
  };

  const handleAddMenuItem = () => {
    const newItemId = menuItems.length > 0 ? menuItems[menuItems.length - 1].id + 1 : 4321;
    const newItem = { id: newItemId, name: '', price: '' };
    setMenuItems([...menuItems, newItem]);
  };

  const handleRemoveMenuItem = (index) => {
    const updatedItems = [...menuItems];
    updatedItems.splice(index, 1);
    setMenuItems(updatedItems);
  };

  const handleMenuItemChange = (e, index, field) => {
    const updatedItems = [...menuItems];
    updatedItems[index][field] = e.target.value;
    setMenuItems(updatedItems);
  };

  const handleFormSubmit = (e) => {
    e.preventDefault();
    // Handle form submission here, e.g., send data to a server
    window.alert('Your details are saved.');
    // Reset form state
    setShowForm(false);
    setEmail('');
    setPassword('');
    setRestaurantName('');
    setMenuItems([{ id: 4321, name: '', price: '' }]);
  };

  return (
    <div className="cook-login-container">
      <h2 className="heading">Welcome home Cooks</h2>
      {!showForm ? (
        <>
          <div className="form-group">
            <label htmlFor="email">Email:</label>
            <input
              type="email"
              id="email"
              name="email"
              value={email}
              onChange={handleEmailChange}
              required
            />
          </div>
          <div className="form-group">
            <label htmlFor="password">Password:</label>
            <input
              type="password"
              id="password"
              name="password"
              value={password}
              onChange={handlePasswordChange}
              required
            />
          </div>
          <button type="button" onClick={handleLoginClick}>Login</button>
        </>
      ) : (
        <div>
          <form onSubmit={handleFormSubmit}>
            <h3 style={{ textAlign: 'center', fontWeight: 'bold' }}>Restaurant Details</h3>
            <div className="form-group">
              <label htmlFor="restaurantName">Restaurant Name:</label>
              <input
                type="text"
                id="restaurantName"
                name="restaurantName"
                value={restaurantName}
                onChange={handleRestaurantNameChange}
                required
              />
            </div>
            <div className="menu-items">
              <h3 style={{ textAlign: 'center', fontWeight: 'bold' }}>Menu</h3>
              {menuItems.map((item, index) => (
                <div key={item.id} className="menu-item">
                  <div className="form-group">
                    <label htmlFor={`itemName-${item.id}`}>Item Name:</label>
                    <input
                      type="text"
                      id={`itemName-${item.id}`}
                      name={`itemName-${item.id}`}
                      value={item.name}
                      onChange={(e) => handleMenuItemChange(e, index, 'name')}
                      required
                    />
                  </div>
                  <div className="form-group">
                    <label htmlFor={`itemPrice-${item.id}`}>Price:</label>
                    <input
                      type="number"
                      id={`itemPrice-${item.id}`}
                      name={`itemPrice-${item.id}`}
                      value={item.price}
                      onChange={(e) => handleMenuItemChange(e, index, 'price')}
                      required
                    />
                  </div>
                  <button type="button" onClick={() => handleRemoveMenuItem(index)}>
                    Remove
                  </button>
                </div>
              ))}
              <button type="button" onClick={handleAddMenuItem}>Add Item</button>
            </div>
            <button type="submit">Save</button>
          </form>
        </div>
      )}
    </div>
  );
};

export default CookLogin;
